export const BUENAS_OBRAS = [
  {
    day: 1,
    personaje: "PINGUINO-1",
    description: "Decorar el árbol de Navidad en familia",
    angelitaText: "Los momentos<br />compartidos son<br />los más valiosos",
  },
  {
    day: 2,
    personaje: "GNOMO",
    description: "Hacer una tarjeta de navidad para la familia",
    angelitaText: "Tu creatividad es el mejor regalo",
  },
  {
    day: 3,
    personaje: "RENO",
    description: "Leer un cuento navideño en familia",
    angelitaText: "Es el momento perfecto para compartir en familia.",
  },
  {
    day: 4,
    personaje: "SANTA",
    description: "Ayudar a las labores de casa con alegría",
    angelitaText: "Las pequeñas acciones hacen la diferencia",
  },
  {
    day: 5,
    personaje: "GALLETA",
    description: "Llamar a un familiar para decirle cuánto lo quieres.",
    angelitaText:
      "Dejemos que el amor navideño brille a través de nuestras palabras",
  },
  {
    day: 6,
    personaje: "OSITO",
    description: "Decir algo amable a cada miembro de tu familia.",
    angelitaText: "Permite que la alegría navideña guíe nuestras palabras.",
  },
  {
    day: 7,
    personaje: "PINGUINO-2",
    description: "Decorar galletas navideñas",
    angelitaText: "Haz de la cocina un lugar de alegría",
  },
  {
    day: 8,
    personaje: "GNOMO",
    description: "Visitar a un ser querido",
    angelitaText: "El mejor regalo es estar juntos",
  },
  {
    day: 9,
    personaje: "RENO",
    description: "Ayudar a preparar la cena.",
    angelitaText:
      "Cocinar en familia es el ingrediente para que tu navidad sea especial",
  },
  {
    day: 10,
    personaje: "SANTA",
    description: "Compartir un juguete con un amigo.",
    angelitaText: "Los momentos compartidos con los más valiosos",
  },
  {
    day: 11,
    personaje: "GALLETA",
    description: "Comer sin dispositivos electrónicos",
    angelitaText: "Regala momentos especiales",
  },
  {
    day: 12,
    personaje: "OSITO",
    description: "Donar un juguete",
    angelitaText: "El mejor regalo es el que viene del corazón.",
  },
  {
    day: 13,
    personaje: "PINGUINO-1",
    description: "Ver una película navideña en familia",
    angelitaText: "El mejor obsequio es la familia",
  },
  {
    day: 14,
    personaje: "GNOMO",
    description: "Hacer un postre en familia",
    angelitaText: "Cocinar juntos une corazones.",
  },
  {
    day: 15,
    personaje: "RENO",
    description: "Hacer una acción amable por un extraño.",
    angelitaText: "Dar es recibir",
  },
  {
    day: 16,
    personaje: "SANTA",
    description: "Recoger tu cuarto.",
    angelitaText: "Disfruta y juega en tu habitación ordenada",
  },
  {
    day: 17,
    personaje: "GALLETA",
    description: "Escribir una lista de cosas por las que agradeces",
    angelitaText: "La gratitud hace brillar las cosas más simples",
  },
  {
    day: 18,
    personaje: "OSITO",
    description: "Hacer un cumplido a tres personas diferentes.",
    angelitaText: "Haz sonreír a alguien hoy",
  },
  {
    day: 19,
    personaje: "PINGUINO-2",
    description: "Hacer un postre en familia",
    angelitaText: "Crea momentos memorables cocinando con quienes amas",
  },
  {
    day: 20,
    personaje: "GNOMO",
    description: "Jugar un juego de mesa en familia",
    angelitaText: "regalemos momentos especiales.",
  },
  {
    day: 21,
    personaje: "RENO",
    description: "Preparar una lista de buenos propósitos para el próximo año.",
    angelitaText: "Cada día es una oportunidad para ser mejor",
  },
  {
    day: 22,
    personaje: "SANTA",
    description: "Hacer un regalo sorpresa para alguien.",
    angelitaText: "Pon tu toque personal en cada detalle y sorprende",
  },
  {
    day: 23,
    personaje: "GALLETA",
    description: "Aprender algo nuevo en familia",
    angelitaText: "El conocimiento nos une",
  },
  {
    day: 24,
    personaje: "OSITO",
    description: "Ayudar a poner la mesa",
    angelitaText: "Que el espíritu navideño resplandezca en cada gesto.",
  },
  {
    day: 25,
    personaje: "PINGUINO-1",
    description: "Disfrutar en familia la alegría de la Navidad",
    angelitaText: "La familia es el mayor regalo",
  },
];
